### PR TITLE
28 remote file upload

### LINKED ISSUE #28: No filename extension appended to extension-less ontology files?
Importing http://omdoc.org/ontology fails with Hets expecting CASL.

BTW note that the right URL is actually http://omdoc.org/ontology#, but this doesn't work at the moment; see #27.

I suspect the cause is that the downloaded file is named "ontology", without a filename extension.

But I thought we had said earlier that, for now, extension-less downloaded files should be renamed to *.owl, as in most cases what you get from such "cool URI" URLs is OWL (or RDF, which Hets does not yet support completely).

### PR DESCRIPTION
**Pull request by 0robustus1**
Should fix #28. Needs the current version of hets.

### CODE REVIEW

File: app/models/repository_file.rb [hunk 1]
```diff
@@ -56,7 +59,29 @@ def initialize(*args, &block)
...
+      @remote_file ||= retrieve(remote_file_iri)
+    end
+  end
+
+  def source_filename
+    case file_upload_type
+    when 'local'
+      temp_file.original_filename
+    when 'remote'
+      remote_file_iri.split('/').last
```
Comment (eugenk) [inline app/models/repository_file.rb]: What if the iri has a query string or ends on `/`?

File: app/assets/javascripts/files.js.coffee [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+  not not reverse_locality(locality)
+
+determine_filetype = (iri, callback) ->
+  payload = iri: iri
+  $.post "/filetypes/", payload, callback, 'json'
+
+determine_filename = (callback) ->
+  iri = $(remote_file_input).val()
+  if iri.length
+    result = iri.match(/\/([^/]+)(\?.*)?$/)
```
Comment (eugenk) [inline app/assets/javascripts/files.js.coffee]: Here, you consider query strings.

File: db/migrate/20141206161905_create_file_extension_mime_type_mappings.rb [hunk 3]
```diff
@@ -0,0 +1,10 @@
+class CreateFileExtensionMimeTypeMappings < ActiveRecord::Migration
+  def change
+    create_table :file_extension_mime_type_mappings do |t|
+      t.string :file_extension, null: false
+      t.string :mime_type, null: false
+
+      t.timestamps
+    end
```
Comment (eugenk) [inline db/migrate/20141206161905_create_file_extension_mime_type_mappings.rb]: How about
```ruby
add_index :file_extension_mime_type_mappings, :mime_type
```
since you call `find_by_mime_type`?

File: db/migrate/20141206163145_add_mappings_to_file_extension_mime_type_mappings.rb [hunk 4]
```diff
@@ -0,0 +1,28 @@
+class AddMappingsToFileExtensionMimeTypeMappings < ActiveRecord::Migration
+  MAPPINGS = {
+    '.clif' => 'text/clif',
+    '.owl' => 'application/owl',
+    '.owl' => 'text/obo',
```
Comment (eugenk) [inline db/migrate/20141206163145_add_mappings_to_file_extension_mime_type_mappings.rb]: You use the key `'.owl'` twice.

File: app/controllers/filetypes_controller.rb [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+  end
+
+  protected
+
+  def filetype
+    @filetype ||= Hets::FiletypeCaller.new(HetsInstance.choose).
+      call(params[:iri])
+  end
+
+  def filetype_json
```
Comment (eugenk) [inline app/controllers/filetypes_controller.rb]: Is it a convention to name a method `_json`, when the return hash is supposed to be rendered as json?

File: app/assets/javascripts/files.js.coffee [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+    callback(result[1], iri) if result
+
+has_fileextension = (filename) ->
+  filename.split('.').length > 1
+
+filename_eligible = ->
```
Comment (eugenk) [inline app/assets/javascripts/files.js.coffee]: I prefer `filename_suggest_eligible`.

**Comment by eugenk** [comment]
Entering the remote address `https://ontohub.org/dol-examples/equiv` into the form, I get the filename suggestion `equivnull`.

File: app/models/repository_file.rb (hunk 1 above)
Comment (0robustus1) [inline app/models/repository_file.rb]: - ends on `/`: we don't care as `split` will take care of this (a lone `/` at the end will just be dropped)
- contains query-string: i will fix that.

File: app/controllers/filetypes_controller.rb (hunk 5 above)
Comment (0robustus1) [inline app/controllers/filetypes_controller.rb]: I believe i've seen this on a few projects. If it however is not a convention, it should now be an ontohub convention to name methods in such a way, don't you think?

File: db/migrate/20141206163145_add_mappings_to_file_extension_mime_type_mappings.rb (hunk 4 above)
Comment (0robustus1) [inline db/migrate/20141206163145_add_mappings_to_file_extension_mime_type_mappings.rb]: Oh yes. I've overlooked that. I change it to use nested lists.

**Comment by 0robustus1** [comment]
Mh i don't get the same issue. For me it suggests: `equiv.het`. Which isn't perfect either but it is what hets returns. Which version of hets are you using?

File: app/controllers/filetypes_controller.rb (hunk 5 above)
Comment (eugenk) [inline app/controllers/filetypes_controller.rb]: Alright.

**Comment by eugenk** [comment]
When I wrote the comment, it said `text/plain`. Now it says `text/het` and the correct extension is suggested.
I don't know why it changed.

**Comment by eugenk** [comment]
:+1:
