### PR TITLE
1707 pagination in ontology mappings is broken

### LINKED ISSUE #1707: Pagination in ontology mapping is broken
e.g. https://ontohub.org/sandbox/animal///mappings

- When clicking any of the pagination buttons, the wrong url is opened (`/sandbox/animal/mappings`).
- The ontology_id is appended as a query parameter, which seems to be unnecessary

Confirmable on master, develop and staging.

### PR DESCRIPTION
**Pull request by phyrog**
This fixes #1707. It also fixes the related global mappings list (`/mappings`), which also had pagination issues.

### CODE REVIEW

File: app/models/mapping.rb [hunk 1]
```diff
@@ -37,11 +37,10 @@ def current
                   :target_id, :versions_attributes, :versions, :name
   accepts_nested_attributes_for :versions
 
-
-  def self.with_ontology_reference(ontology_id)
-    Mapping.where('ontology_id = ? OR source_id = ? OR target_id = ?',
-                          ontology_id, ontology_id, ontology_id)
-  end
+  scope :with_ontology_reference, -> (ontology_id) {
+    where('ontology_id = ? OR source_id = ? OR target_id = ?',
```
Comment (phyrog) [inline app/models/mapping.rb]: Fixed in a283f85

**Comment by ebolloff** [comment]
Pagination raises errors often, so we need to fix it globally in the future. :+1:
