### PR TITLE
1211 fix ref locids for subdirectories

### LINKED ISSUE #1211: loc_ids do not work with subdirectories
see http://develop.ontohub.org/casl-um/new/Chapter3///ontology_versions
the url http://develop.ontohub.org/ref/1/casl-um/Chapter3?path=new is generated and used by hets (the suffix .env is added by hets after this url fails)

### PR DESCRIPTION
**Pull request by 0robustus1**
Shall fix #1211. Additionally provides the migration to update existing data with locids.

### CODE REVIEW

File: spec/models/ontology_version_spec.rb [hunk 1]
```diff
@@ -34,6 +34,26 @@
...
+
+
+      before do
+        ontology_version
+        allow_any_instance_of(Hets::ParseCaller).to receive(:call) do |iri, *args|
+          throw(:iri, iri)
+        end
+      end
+
+      it 'should use the locid-ref for calling the parse-caller' do
```
Comment (0robustus1) [inline spec/models/ontology_version_spec.rb]: Who reactived preference of double-quotes?

Comment (eugenk) [inline spec/models/ontology_version_spec.rb]: Seems to be a bug in hound/rubocop because the yml says:
```yml
Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: true
  Style: 'single_quotes'
  EnforcedStyle: single_quotes
```

**Comment by eugenk** [comment]
Travis fails because of https://github.com/spechub/Hets/issues/1455. This can be merged :+1:
