### PR TITLE
1184 wrong class hierachy tree is displayed

### LINKED ISSUE #1184: Wrong class hierachy tree is displayed
see http://ontohub.org/sandbox/Family///symbols?kind=Class#detail
When clicking on "Class Details", 7 classes are shown, but the hierarchy tree shows only 3 classes.

### PR DESCRIPTION
**Pull request by SGraef**
should fix #1184

### CODE REVIEW

File: lib/tarjan_tree.rb [hunk 1]
```diff
@@ -1,24 +1,27 @@
 # Class for using the Tarjan algorithm to remove cycles in the symbol trees.
 class TarjanTree
   include TSort
-  attr_accessor :hashed_symbols, :subclasses, :ontology
+  attr_accessor :hashed_symbols, :subclasses, :ontology, :symbols, :subclass_sym
```
Comment (eugenk) [inline lib/tarjan_tree.rb]: Please use a plural named variable like `subclass_symbols` instead of `subclass_sym`.

File: lib/tarjan_tree.rb [hunk 2]
```diff
@@ -52,10 +55,15 @@ def create_tree(ontology)
   end
 
   def create_groups(ontology)
+    symbols = self.symbols - subclass_sym
     strongly_connected_components.each do |symbol_ids|
-      symbols = OntologyMember::Symbol.find(symbol_ids)
-      name = group_name_for(symbols)
-      SymbolGroup.create!(ontology: ontology, symbols: symbols, name: name)
+      syms = OntologyMember::Symbol.find(symbol_ids)
```
Comment (eugenk) [inline lib/tarjan_tree.rb]: Please give a more suitable name to the variable `syms`. How about `strongly_connected_symbols` or `equivalent_symbols` or `something_else_symbols`?

File: app/controllers/symbols_controller.rb [hunk 3]
```diff
@@ -18,7 +18,13 @@ def index
     if ontology && (ontology.is?('OWL2') || ontology.is?('OWL'))
       begin
         symbols = ontology.symbol_groups
+        request = <<-SQL
+          id NOT IN (SELECT DISTINCT(parent_id) FROM e_edges
+           UNION SELECT DISTINCT(child_id) FROM e_edges)
+        SQL
+        extra_notes = ontology.symbol_groups.where(request)
```
Comment (eugenk) [inline app/controllers/symbols_controller.rb]: I suppose you meant `extra_nodes` with a "d" ;)
In what way are these "extra"? It seems like they are in a subclass hierarchy somewhere between the child and the parent, but I'm not sure if my guess is correct.

**Comment by eugenk** [comment]
Please add a test

**Comment by eugenk** [comment]
:+1:
