### PR TITLE
1280 hets error handling for proving

### LINKED ISSUE #1280: Add hets error handling to proving feature
When proving, Hets can fail because of several reasons. Examples are
* Unrecognized Hets error (e.g. "Prelude.read: no parse") and an empty HTTP response
* Recognized `Hets::Errors::HetsFileError`

Deal with such errors when proving.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1280. Hets errors are recognized and the states are updated properly.

This only handles errors in the backend. Views for errors and states are part of #1283.

### CODE REVIEW

File: spec/lib/collective_proof_attempt_spec.rb [hunk 1]
```diff
@@ -131,51 +223,147 @@
...
+            expect(theorem.reload.last_error).to include(error_message)
+          end
+        end
+
+        it "ontology_version's last_error contains the error message" do
+          expect(ontology_version.reload.last_error).to include(error_message)
+        end
       end
     end
   end
```
Comment (tillmo) [inline spec/lib/collective_proof_attempt_spec.rb]: Lines 104-155 and 271-322 of this file are identical. Moreover, lines 48-187 and 215-355 are similar. Could this be factored out?

Comment (eugenk) [inline spec/lib/collective_proof_attempt_spec.rb]: For the same reason as in #1298 I decided to have some code duplication in the specs. Again, this operates once on `ontology_version` and once on `theorem`. I can create a context for the identical parts of theorem and ontology_version, if you want me to do it.

Comment (tillmo) [inline spec/lib/collective_proof_attempt_spec.rb]: I think this is a general question about the policy in Ontohub. I let you decide.

**Comment by tillmo** [comment]
:+1:
