### PR TITLE
1251 fix ontology delete

### LINKED ISSUE #1251: Fix ontology delete
Assume you have Ontology P with children C1, C2 in one file. If you want to delete the file or the ontology P, the current code fails because it would delete imported ontologies. In this case, we want to allow the deletion, though.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1251.

--

~~The branch of this pull request is **not based on staging**, but on the one of #1556 (`167-creating_a_new_ontology_version_needs_to_be_propagated`). Revieweing that one first may be easier.~~

~~The first commit of this branch is~~
~~c299dbe Allow to delete an ontology if it is only imported from the same file.~~

### CODE REVIEW

**Comment by eugenk** [comment]
https://github.com/ontohub/ontohub/issues/1251#issuecomment-170032112 is now considered in this branch.

**Comment by eugenk** [comment]
I rebased this on staging

File: spec/models/ontology_spec.rb [hunk 1]
```diff
@@ -147,18 +147,53 @@
...
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'imported by an onology in the same file' do
+        let(:importing) { sibling_ontology }
+        before { create :mapping, target: importing, source: ontology }
+
+        it 'should be allowed' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 2]
```diff
@@ -147,18 +147,53 @@
...
+        let(:importing) { create :ontology, repository: ontology.repository }
+        before { create :mapping, target: importing, source: ontology }
+
+        it 'should not be allowed' do
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'imported by an onology in the same file' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 3]
```diff
@@ -147,18 +147,53 @@
...
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'imported by an onology in the same repository but another file' do
+        let(:importing) { create :ontology, repository: ontology.repository }
+        before { create :mapping, target: importing, source: ontology }
+
+        it 'should not be allowed' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 4]
```diff
@@ -147,18 +147,53 @@
...
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'with sibling imported by an onology in a different repository' do
+        let(:importing) { create :ontology }
+        before { create :mapping, target: importing, source: sibling_ontology }
+
+        it 'should not be allowed' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 5]
```diff
@@ -147,18 +147,53 @@
...
 
-      it 'should not be allowed' do
-        importing = create :ontology
-        create :import_mapping, target: importing, source: ontology
-        expect { ontology.destroy_with_parent(user) }.to raise_error(Ontology::DeleteError)
+      context 'imported by an onology in a different repository' do
+        let(:importing) { create :ontology }
+        before { create :mapping, target: importing, source: ontology }
+
+        it 'should not be allowed' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 6]
```diff
@@ -147,18 +147,53 @@
...
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'with sibling imported by an onology in a different repository' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 7]
```diff
@@ -147,18 +147,53 @@
...
       before do
         stub = ->(_u, _t, _m, &block) { block.call('0'*40) }
         allow_any_instance_of(Repository).to receive(:delete_file, &stub)
       end
 
-      it 'should not be allowed' do
-        importing = create :ontology
-        create :import_mapping, target: importing, source: ontology
-        expect { ontology.destroy_with_parent(user) }.to raise_error(Ontology::DeleteError)
+      context 'imported by an onology in a different repository' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 8]
```diff
@@ -147,18 +147,53 @@
       end
     end
 
-    context 'an imported ontology' do
-      let(:ontology) { create :ontology }
+    context 'an imported ontology (meaning any kind of mapping)' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/models/ontology_spec.rb [hunk 9]
```diff
@@ -147,18 +147,53 @@
...
+        let(:importing) { create :ontology }
+        before { create :mapping, target: importing, source: sibling_ontology }
+
+        it 'should not be allowed' do
+          expect { ontology.destroy_with_parent(user) }.
+            to raise_error(Ontology::DeleteError)
+        end
+      end
+
+      context 'imported by an onology in the same repository but another file' do
```
Comment (eugenk) [inline spec/models/ontology_spec.rb]: I guess this is okay in this case.

File: spec/factories/ontology_factory.rb [hunk 10]
```diff
@@ -118,6 +118,21 @@
...
 
+      trait :with_children do
+        after(:build) do |ontology|
+          ontology.children << FactoryGirl.build(:ontology,
+            parent: ontology,
+            repository: ontology.repository,
+            basepath: ontology.basepath,
+            file_extension: ontology.file_extension)
+          ontology.children << FactoryGirl.build(:ontology,
+            parent: ontology,
```
Comment (eugenk) [inline spec/factories/ontology_factory.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: spec/factories/ontology_factory.rb [hunk 11]
```diff
@@ -118,6 +118,21 @@
         end
       end
 
+      trait :with_children do
+        after(:build) do |ontology|
+          ontology.children << FactoryGirl.build(:ontology,
+            parent: ontology,
```
Comment (eugenk) [inline spec/factories/ontology_factory.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: app/views/ontologies/_menu.html.haml [hunk 12]
```diff
@@ -29,4 +29,4 @@
           %ul.dropdown-menu{role: 'menu'}
             - %w(xml json).each do |f|
               %li= link_to f.upcase, format: f
-= modal_body("header_text", t('ontology.delete_confirm.text', name: resource, parent_text: resource.parent.present? ? t('ontology.delete_confirm.parent') : '', children_text: resource.children.present? ? t('ontology.delete_confirm.children') : '', path: resource.path), resource_chain, t('ontology.delete'))
+= modal_body(t('ontology.delete_confirm.header_text', oms: Settings.OMS), t('ontology.delete_confirm.text', name: resource, parent_text: resource.parent.present? ? t('ontology.delete_confirm.parent') : '', children_text: resource.children.present? ? t('ontology.delete_confirm.children') : '', path: resource.path), resource_chain, t('ontology.delete'))
```
Comment (eugenk) [inline app/views/ontologies/_menu.html.haml]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: app/views/ontologies/_menu.html.haml [hunk 13]
```diff
@@ -18,7 +18,7 @@
         - if resource.can_be_deleted?
           = modal_button(t('ontology.delete'), btn_class: 'btn-default')
         - else
-          .btn.btn-default.tooltip-btn{ disabled: true, data: { toggle: "tooltip", :'original-title' => t('ontology.delete_error', oms: Settings.OMS), container: 'body' } }
+          .btn.btn-default.tooltip-btn{ disabled: true, data: { toggle: "tooltip", :'original-title' => t('ontology.delete_error', oms_with_article: Settings.OMS.with_indefinite_article, oms: Settings.OMS), container: 'body' } }
```
Comment (eugenk) [inline app/views/ontologies/_menu.html.haml]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

File: app/controllers/ontologies_controller.rb [hunk 14]
```diff
@@ -73,13 +73,14 @@ def show
...
-    if resource.is_imported?
-      flash[:error] = "Can't delete #{Settings.OMS.with_indefinite_article}
-      that is imported by another one."
-      redirect_to resource_chain
-    else
+    if resource.can_be_deleted?
       resource.destroy_with_parent(current_user)
       destroy!
+    else
+      flash[:error] = t('ontology.delete_error',
```
Comment (eugenk) [inline app/controllers/ontologies_controller.rb]: No thanks. You should stop suggesting this as soon as #1574 gets merged.

**Comment by SGraef** [comment]
:+1:
